styled registration form/added state/registration function
chuckchoiboi/melophied pull request #29
Opened 2021-03-15 01:04 UTC by meganmatthews44

2021-03-15 01:12 UTC, jennuwine commented
looks good to me Megan

2021-03-15 04:06 UTC, chuckchoiboi requested changes
I think it all looks good, but couple changes for the form elements. Seems like you forgot to change the controlId for the form fields. Also, can we change confirm-password name to password2 field to avoid hyphenated names and use camel case format?

Lastly, If we could make the form into a RegistrationForm component, that would be amazing!

2021-03-15 04:06 UTC, chuckchoiboi commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +        <Form.Group controlId="confirm-password">
controlId will need to change to firstName

2021-03-15 04:06 UTC, chuckchoiboi commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +        <Form.Group controlId="confirm-password">
controlId will need to change to lastName

2021-03-15 04:06 UTC, chuckchoiboi commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +        <Form.Group controlId="confirm-password">
controlId will need to change to email

2021-03-15 04:06 UTC, chuckchoiboi commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +        <Form.Group controlId="confirm-password">
can we change the controlId and name field to password2 instead? I think it works either way but I think it is good to use camel case instead of hyphen for variable names and form field names

2021-03-15 04:06 UTC, chuckchoiboi commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +        <Form.Control type="password" placeholder="Confirm Password" name="confirm-password" />
Can we add onChange call back for setPassword2

2021-03-15 04:06 UTC, chuckchoiboi commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +        Already have a Melophied account?
Love this idea!

2021-03-16 01:48 UTC, meganmatthews44 commented on src/pages/RegistrationPage/RegistrationPage.jsx
> +          history.push('/')
push changes to '/login'

2021-03-16 03:29 UTC, chuckchoiboi requested changes
as long as you invoke useHistory(), it looks golden!

2021-03-16 03:29 UTC, chuckchoiboi commented on src/components/RegistrationForm/RegistrationForm.jsx
> +    const history = useHistory;
You'd have to invoke useHistory function with parenthesis

2021-03-17 01:25 UTC, merged