routed to login/create page based on currentUser
chuckchoiboi/melophied pull request #72
Opened 2021-03-18 05:03 UTC by meganmatthews44

2021-03-18 06:15 UTC, chuckchoiboi requested changes
Looks good! Just minor changes

2021-03-18 06:15 UTC, chuckchoiboi commented on src/config/router.js
> +        <Route exact path="/" render={(props) =>  <HomePage currentUser={currentUser}/>  }/>
I think this should work without (props), but instead () since currentUser is destructured at line 9 (Routes). Could you check if it does? If it does, can we make it

`<Route exact path="/" render={() =>  <HomePage currentUser={currentUser}/>  }/>`

2021-03-18 06:15 UTC, chuckchoiboi commented on src/pages/App/App.js
> +import HomePage from '../../pages/HomePage/HomePage';
I think we can get rid of this, HomePage is not used in App.js but in Routes component

2021-03-19 02:38 UTC, meganmatthews44 commented on src/pages/App/App.js
> +import HomePage from '../../pages/HomePage/HomePage';
Good catch! Forgot to remove from my first try!

2021-03-19 02:39 UTC, meganmatthews44 commented on src/config/router.js
> +        <Route exact path="/" render={(props) =>  <HomePage currentUser={currentUser}/>  }/>
yup, it works without props! changes made!

2021-03-19 15:48 UTC, chuckchoiboi approved these changes

2021-03-19 15:48 UTC, chuckchoiboi commented
Looks good to me!

2021-03-19 21:37 UTC, merged